paths:
  metadata_path: '/home/maxime/data/jump_embeddings/metadata_openphenom.parquet'
  embeddings_path: '/home/maxime/data/jump_embeddings/embeddings_openphenom.npy'
  exp_folder: "/home/maxime/synrepos/phenoseeker/tmp/openphenom"
  exp_name: "48_plates_4_combi"

methods:
  - apply_inverse_normal_transform
  - apply_rescale
  - apply_spherizing_transform
  - apply_robust_Z_score
  - apply_median_polish

max_combinations: 100000
n_methods_max: 4 # Should not be higther than n_methods
# If not specified or all, the whole JUMP will be used

#  or balance_selection, a balanced selection to test all normalisations
#selected_plates: 
#  - EC000010
#  - GR00004379
#  - A1170386

selected_plates: "balance_selection"