paths:
  metadata_path: '/projects/synsight/data/jump_embeddings/wells_embeddings/dinov2_g/metadata_dinov2_g.parquet'
  embeddings_path: '/projects/synsight/data/jump_embeddings/wells_embeddings/dinov2_g/embeddings_dinov2_g.npy'
  exp_folder: "/projects/synsight/repos/phenoseeker/tmp/dinov2_g"
  exp_name: "48_plates_4_combi"

methods:
  - apply_inverse_normal_transform
  - apply_rescale
  - apply_spherizing_transform
  - apply_robust_Z_score
  - apply_median_polish

max_combinations: 100000
n_methods_max: 4 # Should not be higther than n_methods
# If not specified or all, the whole JUMP will be used

#  or balance_selection, a balanced selection to test all normalisations
#selected_plates: 
#  - EC000010
#  - GR00004379
#  - A1170386

selected_plates: "balance_selection"