paths:
  metadata_path: '/home/maxime/synrepos/phenospace/jump_pl/images_embeddings/ResNet50/metadata/load_wells/load_wells.parquet'
  exp_folder: "/home/maxime/synrepos/phenoseeker/tmp/resnet"
  exp_name: "all_jump_3_norm"

methods:
  - apply_inverse_normal_transform
  - apply_rescale
  - apply_spherizing_transform
  - apply_robust_Z_score

max_combinations: 3
n_methods_max: 1 # Should not be higther than n_methods

selected_plates: # If not specified or all, the whole JUMP will be used
  - EC000010
  - GR00004379
  - A1170386

#selected_plates: "all"